menu:
  Home: /
  Archives: /archives
  Projects: /projects
  About: /about

widgets:
- profile
- search
- recent_posts
- category
- tagcloud
- weibo
- links

excerpt_link: 阅读全文

jiathis:
  enable: true

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true
baidu_tongji: f4eb406be058265cf6064b36b379393d
rss: 

comment_provider: duoshuo
duoshuo_shortname: noahgao
# Facebook comment
#facebook:
  #appid: 123456789012345
  #comment_count: 5
  #comment_width: 840
  #comment_colorscheme: light